apiVersion: v1          # for pods > v1     #can check with > kubectl api-resources
kind: Pod
metadata:               #information about object
  name: nginx-pod
  labels:               #identifiers to the pods
    team: integration
    app: todo          
spec:                   #actual specification of the resource
  containers: 
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80 
